baseURL = 'https://yunea.github.io/ainablog/'
languageCode = 'fr'
title = 'Aina'
theme = 'pehtheme-hugo'

pagination.pagerSize = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Mon portfolio.'
	mainSections = 'posts'

[params.author]
	name = 'Aïna Dirou'
	bio = 'Ma bio'
	avatar = '/images/nasa-astronaut-unsplash.jpg'
	twitter = 'https://twitter.com/insertapps'

[menu] # Menu management
	[[menu.main]]
		name = 'Accueil'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'CV'
		pageRef = '/cv'
		weight = 15
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'Taxonomy'
		pageRef = '/tags/post/'
		weight = 25

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'